name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno 0.40
        uses: denolib/setup-deno@220d9c6
        with:
          deno-version: '0.40'
      - run: deno fmt --check
      - run: deno test -A
